---
title: Team Elam
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
tagline: a family story
description: This is our story, our home away from home, and our adventures as a team.
  Welcome to Team Elam :)
url: http://teamelam.com
baseurl: '/'
paginate: 10
author: Jennifer
name: Jennifer Elam
email: jen@mommyknowsbest.co
version: 1.0.0
gems:
- jekyll-paginate
markdown: kramdown
