---
title: Team Elam
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: pretty
tagline: a family story
description: This is our story, our home away from home, and our adventures as a team.
  Welcome to Team Elam :)
url: 
baseurl: ""
paginate: 5
author: Jennifer
name: Jennifer Elam
email: jen@mommyknowsbest.co
version: 1.0.0
gems:
- jekyll-paginate
